---
openapi: 3.0.1
info:
  title: BlueOcean Blog api v1
  description: This is desciption
  version: v1

paths:
  /api/v1/auth/sign_up:
    $ref: "paths/auth/registers.yaml#/sign_up"

servers:
- url: http://localhost:3000/
  variables:
    defaultHost:
      default: www.example.com

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
